# Arrays 

In [7]:
import numpy as np
a=input().split()
print(np.array(a[::-1],float))

1 2 3
[3. 2. 1.]


# Shape and reshape

In [17]:
a=list(map(int,input().split() ))
aa=np.array(a)
print(np.reshape(aa,(3,3)))

1 3 4 5 6 7 8 9 2
[[1 3 4]
 [5 6 7]
 [8 9 2]]


# Transpose and Flatten

In [24]:

n, m = map(int, input().split())
array = np.array([input().strip().split() for _ in range(n)], int)
print(array)


6 7
8 7
6 7
8 7
9 0
76 7
6 5
[[ 8  7]
 [ 6  7]
 [ 8  7]
 [ 9  0]
 [76  7]
 [ 6  5]]


# Concatenate

In [31]:
import numpy as np
a,c,b=map(int,input().split())


arr1=np.array([input().split() for _ in range(a)],int)
arr2=np.array([input().split() for _ in range(c)],int)
print(np.concatenate((arr1,arr2),axis=0))


2 3 4
2 3
4 5
3 4
4 5
6 7
[[2 3]
 [4 5]
 [3 4]
 [4 5]
 [6 7]]


# Zeros and Ones

In [41]:
a=tuple(map(int,input().split()))
print(np.zeros(a,dtype=int))
print(np.ones(a,dtype=int))




2 3
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]


# Min and Max 

In [69]:
a,b=map(int,input().split())
arr=np.array([input().split() for _ in range(a)],int)
x=print(np.max(np.min(arr,axis=1)))


3 4
2 3
4 5
3 6
4


# Sum and Prod

In [72]:
a,b=map(int,input().split())
arr=np.array([input().split() for _ in range(a)],int)

print(np.prod(np.sum(arr,axis=0)))

3 4
4 5
6 7
7 8
340



# Dot and cross product

In [82]:
n=int(input())
array1=np.array([input().split() for _ in range(n)],int)
array2=np.array([input().split() for _ in range(n)],int)
print(np.dot(array1,array2))

2
3 4
2 3
4 5
6 7
[[36 43]
 [26 31]]


# Eye and Identity

In [6]:
import numpy as np
n,m=map(int,input().split())
np.set_printoptions(legacy="1.13")
print(np.eye(n,m))

3 4
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]]


# Array Mathematics

In [9]:
import numpy as np
n,m=map(int,input().split())
A=np.array([input().split() for _ in range(n)],int)
B=np.array([input().split() for _ in range(n)],int)
print(A+B,A-B,A*B,A//B,A%B,A**B,sep="\n")

2 3
3
2
4
5
[[7]
 [7]]
[[-1]
 [-3]]
[[12]
 [10]]
[[0]
 [0]]
[[3]
 [2]]
[[81]
 [32]]


# Floor,ceil and rint

In [14]:
a=np.array(input().split(),float)
np.set_printoptions(legacy="1.13")
print(np.floor(a),np.ceil(a),np.rint(a),sep="\n")

2.2 3.4 5.5 6.7 8.8 9.9 1.23
[ 2.  3.  5.  6.  8.  9.  1.]
[  3.   4.   6.   7.   9.  10.   2.]
[  2.   3.   6.   7.   9.  10.   1.]


# Inner and Outer

In [15]:
A,B=(np.array(input().split(),int) for _ in range(2))
print(np.inner(A,B),np.outer(A,B),sep="\n")

2 3 4 5
5 6 7 8
96
[[10 12 14 16]
 [15 18 21 24]
 [20 24 28 32]
 [25 30 35 40]]


# polynomial

In [20]:
n=int(input())
a=list(map(float,input().split()))
print(np.polyval(a,n))

3
2 3 4
31.0


# Linear Algebra

In [17]:
n=int(input())
arr=np.array([input().split() for _ in range(n)],float)
print(round(np.linalg.det(arr),2))

2
2.2 3.4
2.5 6.7
6.24


# Mean,var and std 

In [22]:
n,m=map(int,input().split())
arr=np.array([input().split() for _ in range(n)],float)
print(np.mean(arr,axis=1),np.var(arr,axis=0),sep="\n")
print(np.around(np.std(arr),decimals=11))

3 4
3 
4
5
[ 3.  4.  5.]
[ 0.66666667]
0.81649658093
